#!/usr/bin/bash

source ~/.bash/aliases

source ~/.bash/completions/git
complete -o default -o nospace -F _git_checkout gco
complete -o default -o nospace -F _git_branch gb
complete -o default -o nospace -F _git_commit gc
complete -o default -o nospace -F _git_diff gd
complete -o default -o nospace -F _git_diff gdc
complete -o default -o nospace -F _git_diff gdcs
complete -C ~/.bash/completions/rake -o default rake
complete -C ~/.bash/completions/project -o default c
complete -C ~/.bash/completions/project -o default cm
complete -C ~/.bash/completions/capistrano -o default cap

# prompt: [ root ~ master +? ] % cmd
_user_root() { [ $USER == "root" ] && printf 'root '; }
_ruby_version() { local v=$(ruby ~/.bash/ruby_version.rb); printf "$v"; }

if [[ 'hostname -s' -eq "<COMPUTER_HOSTNAME>" ]];
then
  export PS1="\[\e[0;35m\]me \$(_user_root)\[\e[33m\]\w\e[31m\]\$(__git_ps1)\[\e[36m\] \$(_ruby_version)\n\[\e[33m\]\[\e[32;1m\]$\[\e[0m\] "
else
  export PS1="\[\e[0;35m\]\u\[\e[33m\]@\[\e[36m\]\h \$(_user_root)\[\e[33m\]\w\e[31m\]\$(__git_ps1)\[\e[36m\]\$(_rvm_prompt)\n\[\e[33m\]\[\e[32;1m\]$\[\e[0m\] "
fi

### Bash http://blog.macromates.com/2008/working-with-history-in-bash/
export HISTCONTROL=erasedups
export HISTSIZE=10000
shopt -s histappend

### COLORS
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

export BUNDLER_EDITOR=subl
export VISUAL="nano"
export EDITOR="nano"
